#version 450

#define NO_SELECT 0
#define TRIANGLE_SELECT 1
#define VERTEX_SELECT 2
#define EDGE_SELECT 3
#define EPS 0.000001

struct RayGenerator {
    uint tid;
    float distance;
};

struct Ray {
    vec3 position;
    vec3 direction;
};

struct Triangle {
    uint hole;
    uint a;
    uint b;
    uint c;
};

layout(binding = 0) buffer RayGeneratorSSBOIn {
   RayGenerator raygenIn[ ];
};

layout(binding = 1) buffer OverlaySSBO {
	uint hovered_tid;
    uint hovered_edge_v1;
    uint hovered_edge_v2;
    vec2 vertex_position;
    vec2 selected_vertex_position;
};

layout(binding = 2) readonly buffer TriangleSSBOIn {
    Triangle triangleIn[ ];
};

layout(binding = 3) readonly buffer VertexSSBOIn {
    vec3 vertexIn[ ];
};

layout(binding = 4) uniform OverlayUniformBufferObject {
	uint mouse_x;
    uint mouse_y;
	uint image_width;
	uint image_height;
	uint single_selected_tid;
    uint single_selected_vid;
    uint single_selected_edge_v1;
    uint single_selected_edge_v2;
    uint mode;
} o_ubo;

layout(binding = 5) uniform UniformBufferObject {
    vec3 look;
    vec3 position;
    vec3 up;
    vec3 u;
    vec3 v;
    vec3 w;
    vec2 viewport;
    uint triangles;
    uint grid;
    float fov;
    float width;
    float height;
    uint orthogonal;
    float depth;
    uint edgemode;
} ubo;

layout (local_size_x = 256, local_size_y = 1, local_size_z = 1) in;

Ray create_ray(vec2 rg) {
    float r = ubo.width / 2.0;
    float b = ubo.height / 2.0;
    float l = -1.0 * r;
    float t = -1.0 * b;
    float u = l + ((r - l) * (float(rg.x) + 0.5)) / ubo.width;
    float v = b + ((t - b) * (float(rg.y) + 0.5)) / ubo.height;
    float d = (cos(ubo.fov / 2.0) / sin(ubo.fov / 2.0)) * r;
    Ray ray;
    if (ubo.orthogonal == 1) {
        float cam_dist = length(ubo.position);
        float aspect = ubo.width / ubo.height;
        float u_n = (u / ubo.width) * aspect;
        float v_n = v / ubo.height;
        ray.direction = normalize(-ubo.w);
        ray.position  = ubo.position + (ubo.u * u_n * cam_dist) + (ubo.v * v_n * cam_dist);
    } else {
        ray.direction = normalize((ubo.u * u) + (ubo.v * v) - (ubo.w * d));
        ray.position  = ubo.position;
    }
    return ray;
}

vec2 project_vertex(vec3 vertex) {
    vec3 rel = vertex - ubo.position;
    float cx = dot(rel, ubo.u);
    float cy = dot(rel, ubo.v);
    float cz = dot(rel, -ubo.w);
    float r = ubo.width * 0.5;
    float b = ubo.height * 0.5;
    float d = (cos(ubo.fov / 2.0) / sin(ubo.fov / 2.0)) * r;
    float px = (cx / cz) * d;
    float py = (cy / cz) * d;
    float sx = ((px + r) / (2.0 * r)) * ubo.width;
    float sy = ((b - py) / (2.0 * b)) * ubo.height;
    return vec2(sx - 0.5, sy - 0.5);
}

void main() {
    if (gl_GlobalInvocationID.x == 0 && o_ubo.single_selected_vid != -1)
        selected_vertex_position = project_vertex(vertexIn[o_ubo.single_selected_vid]);
	int rx = int(gl_GlobalInvocationID.x%int(o_ubo.image_width));
    int ry = int(gl_GlobalInvocationID.x/int(o_ubo.image_width));
    if (rx == o_ubo.mouse_x && ry == o_ubo.mouse_y) {
        if (o_ubo.mode == TRIANGLE_SELECT) {
		    hovered_tid = raygenIn[gl_GlobalInvocationID.x].tid;
        } else if (o_ubo.mode == VERTEX_SELECT) {
            Ray ray = create_ray(vec2(rx, ry));
            Triangle tri = triangleIn[raygenIn[gl_GlobalInvocationID.x].tid];
            vec3 _a = vertexIn[tri.a];
            vec3 _b = vertexIn[tri.b];
            vec3 _c = vertexIn[tri.c];
            vec3 e1 = _b - _a;
            vec3 e2 = _c - _a;
            vec3 h = cross(ray.direction, e2);
            float a = dot(e1, h);
            if (abs(a) < EPS) return;
            float f = 1.0 / a;
            vec3 s = ray.position - _a;
            float u = f*dot(s, h);
            if (u < 0.0 || u > 1.0) return;
            vec3 q = cross(s, e1);
            float v = f*dot(ray.direction, q);
            if (v < 0.0 || u + v > 1.0) return;
            float w = 1.0f - u - v;
            hovered_tid = (u > v && u > w) ? tri.b : (v > w ? tri.c : tri.a);
            vertex_position = project_vertex(vertexIn[hovered_tid]);
        } else if (o_ubo.mode == EDGE_SELECT) {
            hovered_edge_v1 = -1;
            hovered_edge_v2 = -1;
            Ray ray = create_ray(vec2(rx, ry));
            Triangle tri = triangleIn[raygenIn[gl_GlobalInvocationID.x].tid];
            vec3 _a = vertexIn[tri.a];
            vec3 _b = vertexIn[tri.b];
            vec3 _c = vertexIn[tri.c];
            vec3 e1 = _b - _a;
            vec3 e2 = _c - _a;
            vec3 h = cross(ray.direction, e2);
            float a = dot(e1, h);
            if (abs(a) < EPS) return;
            float f = 1.0 / a;
            vec3 s = ray.position - _a;
            float u = f*dot(s, h);
            if (u < 0.0 || u > 1.0) return;
            vec3 q = cross(s, e1);
            float v = f*dot(ray.direction, q);
            if (v < 0.0 || u + v > 1.0) return;
            float w = 1.0f - u - v;
            if (u < v && u < w) {
                hovered_edge_v1 = tri.a;
                hovered_edge_v2 = tri.c;
            } else if (v < w) {
                hovered_edge_v1 = tri.a;
                hovered_edge_v2 = tri.b;
            } else {
                hovered_edge_v1 = tri.b;
                hovered_edge_v2 = tri.c;
            }
        }
    }
}
