#version 450

#define EDGE_RADIUS 0.05

struct BVHNode {
    vec3 minBB;
    vec3 maxBB;
    uint left;
    uint right; // 0xFFFFFFFF if leaf
    uint parent;
    uint counter;
};

struct Triangle {
    uint hole;
    uint a;
    uint b;
    uint c;
};

struct BoundingBox {
    vec3 minBB;
    vec3 maxBB;
};

struct Edge {
    uint a;
    uint b;
    uint f1e1;
    uint f1e2;
    uint f2e1;
    uint f2e2;
    uint f3e1;
    uint f3e2;
    uint f4e1;
    uint f4e2;
    int flow;
    int prev;
};

layout(binding = 0) uniform GeometryUniformBufferObject { 
    vec3 minBB;
    vec3 maxBB;
} ubo;

layout(binding = 1) buffer MortonSSBOIn {
   uint mortonIn[ ];
};

layout(binding = 2) readonly buffer TriangleSSBOIn {
    Triangle triangleIn[ ];
};

layout(binding = 3) readonly buffer VertexSSBOIn {
    vec3 vertexIn[ ];
};

layout(binding = 4) buffer IndexSSBOIn {
    uint indexIn[ ];
};

layout(binding = 5) buffer BoundingBoxSSBOIn {
    BoundingBox bbIn[ ];
};

layout(binding = 6) readonly buffer EdgeSSBOIn {
    Edge edgeIn[ ];
};

layout(binding = 7) uniform UniformBufferObject {
    vec3 look;
    vec3 position;
    vec3 up;
    vec3 u;
    vec3 v;
    vec3 w;
    vec2 viewport;
    uint triangles;
    uint grid;
    float fov;
    float width;
    float height;
    uint orthogonal;
    float depth;
    uint edgemode;
} uubo;

layout(push_constant) uniform PushConstants {
    uint elements;
    uint bitstart;
} pc;

layout (local_size_x = 256, local_size_y = 1, local_size_z = 1) in;

uint expandBits(uint v) {
    v = (v * 0x00010001u) & 0xFF0000FFu;
    v = (v * 0x00000101u) & 0x0F00F00Fu;
    v = (v * 0x00000011u) & 0xC30C30C3u;
    v = (v * 0x00000005u) & 0x49249249u;
    return v;
}

uint interleaveBits(uint x, uint y, uint z) {
    return (expandBits(x) << 0) | (expandBits(y) << 1) | (expandBits(z) << 2);
}

void main() {
    if (uubo.edgemode != 0) {
        uint edgeID = gl_GlobalInvocationID.x;
        if (edgeID >= pc.elements) return;
        indexIn[edgeID] = edgeID;
        Edge edge = edgeIn[edgeID];
        vec3 a = vertexIn[edge.a];
        vec3 b = vertexIn[edge.b];
        vec3 center = (a + b) / 2.0;
        vec3 normalized_center = (center - ubo.minBB) / (ubo.maxBB - ubo.minBB);
        uint x = uint(clamp(normalized_center.x * 1024.0, 0.0, 1023.0));
        uint y = uint(clamp(normalized_center.y * 1024.0, 0.0, 1023.0));
        uint z = uint(clamp(normalized_center.z * 1024.0, 0.0, 1023.0));
        mortonIn[edgeID] = interleaveBits(x, y, z);
        bbIn[edgeID].minBB = min(a, b) - vec3(EDGE_RADIUS);
        bbIn[edgeID].maxBB = max(a, b) + vec3(EDGE_RADIUS);
    } else {
        uint triID = gl_GlobalInvocationID.x;
        if (triID >= pc.elements) return;
        indexIn[triID] = triID;
        Triangle tri = triangleIn[triID];
        vec3 a = vertexIn[tri.a];
        vec3 b = vertexIn[tri.b];
        vec3 c = vertexIn[tri.c];
        vec3 center = (a + b + c) / 3.0;
        vec3 normalized_center = (center - ubo.minBB) / (ubo.maxBB - ubo.minBB);
        uint x = uint(clamp(normalized_center.x * 1024.0, 0.0, 1023.0));
        uint y = uint(clamp(normalized_center.y * 1024.0, 0.0, 1023.0));
        uint z = uint(clamp(normalized_center.z * 1024.0, 0.0, 1023.0));
        mortonIn[triID] = interleaveBits(x, y, z);
        bbIn[triID].minBB = min(a, min(b, c));
        bbIn[triID].maxBB = max(a, max(b, c));
    }
}
