#version 450

#define NO_SELECT 0
#define TRIANGLE_SELECT 1
#define VERTEX_SELECT 2
#define EDGE_SELECT 3
#define EPS 0.000001

struct RayGenerator {
    uint tid;
    float distance;
};

struct Triangle {
    uint hole;
    uint a;
    uint b;
    uint c;
};

struct Ray {
    vec3 position;
    vec3 direction;
};

layout(binding = 0) readonly buffer RayGeneratorSSBOIn {
   RayGenerator raygenIn[ ];
};

layout(binding = 1, rgba8) uniform image2D outputImage;

layout(binding = 2) uniform OverlayUniformBufferObject {
	uint mouse_x;
    uint mouse_y;
	uint image_width;
	uint image_height;
	uint single_selected_tid;
    uint single_selected_vid;
    uint single_selected_eid;
    uint single_selected_edge_v1;
    uint single_selected_edge_v2;
    uint mode;
} o_ubo;

layout(binding = 3) uniform GeometryUniformBufferObject { 
    vec3 minBB;
    vec3 maxBB;
} g_ubo;

layout(binding = 4) buffer OverlaySSBO {
	uint hovered_tid;
    uint hovered_edge_v1;
    uint hovered_edge_v2;
    vec2 vertex_position;
    vec2 selected_vertex_position;
};

layout(binding = 5) readonly buffer VertexSSBOIn {
    vec4 vertexIn[ ];
};

layout(binding = 6) readonly buffer TriangleSSBOIn {
    Triangle triangleIn[ ];
};

layout(binding = 7) uniform UniformBufferObject {
    vec3 look;
    vec3 position;
    vec3 up;
    vec3 u;
    vec3 v;
    vec3 w;
    vec2 viewport;
    uint triangles;
    uint grid;
    float fov;
    float width;
    float height;
    float depth;
    uint edgemode;
    uint viewmode;
    uint geomode;
    float time;
} ubo;

layout (local_size_x = 256, local_size_y = 1, local_size_z = 1) in;

const float vhighlight_radius = 50.0;
const float mixfactor = 0.2;
vec4 highlight_color;
vec4 lock_color;

void calculate_highlight_color() {
    highlight_color = vec4(1.0, 0.52, 0.0, 1.0);
    lock_color = vec4(0.9, 0.12, 0.05, 1.0);
}

void camera_basis(vec3 position, vec3 look, vec3 up, out vec3 u, out vec3 v, out vec3 w) {
    w = normalize(position - look);
    u = normalize(cross(up, w));
    v = cross(w, u);
}

Ray create_ray(vec2 rg) {
    vec3 c_u = ubo.u;
    vec3 c_v = ubo.v;
    vec3 c_w = ubo.w;
    vec3 c_pos = ubo.position;
    vec3 c_look = ubo.look;
    vec3 c_up = ubo.up;
    if (ubo.viewmode > 1) {
        uint quadrant = rg.x < ubo.width / 2.0 ? (rg.y < ubo.height / 2.0 ? 0 : 2) : (rg.y <  ubo.height / 2.0 ? 1 : 3);
        float xleft = ceil(((ubo.width - ubo.viewport.x) / 2.0));
        float ytop = ceil(((ubo.height - ubo.viewport.y) / 2.0));
        float xslice = rg.x < ubo.width / 2.0 ? rg.x - xleft : rg.x - (ubo.width / 2.0);
        float yslice = rg.y < ubo.height / 2.0 ? rg.y - ytop : rg.y - (ubo.height / 2.0);
        rg.x = xslice * 2.0 + xleft;
        rg.y = yslice * 2.0 + ytop;
        float ulen = length(ubo.position);
        if (ubo.viewmode == 2) {
            if (quadrant == 0) {
                c_pos = vec3(ulen, 0, 0);
                c_look = vec3(-1, 0, 0);
            } else if (quadrant == 1) {
                c_pos = vec3(0, 0, ulen);
                c_look = vec3(0, 0, -1);
            } else if (quadrant == 2) {
                c_pos = vec3(0, ulen, 0);
                c_look = vec3(0, -1, 0);
                c_up = vec3(1, 0, 0);
            } else {
                c_pos = vec3(0, -ulen, 0);
                c_look = vec3(0, 1, 0);
                c_up = vec3(1, 0, 0);
            }
            camera_basis(c_pos, c_look, c_up, c_u, c_v, c_w);
        } else if (ubo.viewmode == 3) {
            if (quadrant == 0) {
                c_pos = normalize(vec3(0.7, 1 , 0)) * ulen;
                c_look = normalize(vec3(-1, -1, 0));
            } else if (quadrant == 1) {
                c_pos = normalize(vec3(0.7, -1 , 0)) * ulen;
                c_look = normalize(vec3(-1, 1, 0));
            } else if (quadrant == 2) {
                c_pos = normalize(vec3(0, 1 , 0.7)) * ulen;
                c_look = normalize(vec3(0, -1, -1));
            } else {
                c_pos = normalize(vec3(0, -1 , 0.7)) * ulen;
                c_look = normalize(vec3(0, 1, -1));
            }
            camera_basis(c_pos, c_look, c_up, c_u, c_v, c_w);
        } else {
            if (quadrant == 0) {
                c_pos = normalize(vec3(0.7, 1 , 0.7)) * ulen;
                c_look = normalize(vec3(-1, -1, -1));
            } else if (quadrant == 1) {
                c_pos = normalize(vec3(0.7, -1 , 0.7)) * ulen;
                c_look = normalize(vec3(-1, 1, -1));
            } else if (quadrant == 2) {
                c_pos = normalize(vec3(-0.7, 1 , 0.7)) * ulen;
                c_look = normalize(vec3(1, -1, -1));
            } else {
                c_pos = normalize(vec3(-0.7, -1 , 0.7)) * ulen;
                c_look = normalize(vec3(1, 1, -1));
            }
            camera_basis(c_pos, c_look, c_up, c_u, c_v, c_w);
        }
    }
    float r = ubo.width / 2.0;
    float b = ubo.height / 2.0;
    float l = -1.0 * r;
    float t = -1.0 * b;
    float u = l + ((r - l) * (float(rg.x) + 0.5)) / ubo.width;
    float v = b + ((t - b) * (float(rg.y) + 0.5)) / ubo.height;
    float d = (cos(ubo.fov / 2.0) / sin(ubo.fov / 2.0)) * r;
    Ray ray;
    if (ubo.viewmode > 0) {
        float cam_dist = length(c_pos);
        float aspect = ubo.width / ubo.height;
        float u_n = (u / ubo.width) * aspect;
        float v_n = v / ubo.height;
        ray.direction = normalize(-c_w);
        ray.position  = c_pos + (c_u * u_n * cam_dist) + (c_v * v_n * cam_dist);
        ray.position -= c_w * ubo.depth;
    } else {
        ray.direction = normalize((ubo.u * u) + (ubo.v * v) - (ubo.w * d));
        ray.position  = ubo.position;
        float w_component = dot(ray.direction, -ubo.w);
        ray.position += ray.direction * (ubo.depth / w_component);
    }
    return ray;
}

void highlight_triangle(uint htid) {
	int rx = int(gl_GlobalInvocationID.x%o_ubo.image_width);
    int ry = int(gl_GlobalInvocationID.x/o_ubo.image_width);
    vec4 hcolor = highlight_color;
    if (triangleIn[htid].hole != 0) hcolor = lock_color;
    if (htid != -1 && raygenIn[gl_GlobalInvocationID.x].tid == htid) {
        int radius = 2;
		int minx = 0;
		int miny = 0;
		int maxx = rx;
		int maxy = ry;
		if (rx > radius) minx = rx - radius;
		if (ry > radius) miny = ry - radius;
		if (maxx + radius < o_ubo.image_width) maxx += radius;
		if (maxy + radius < o_ubo.image_height) maxy += radius;
		bool border = false;
		for (int x = minx; x < maxx; x++) {
			for (int y = miny; y < maxy; y++) {
				RayGenerator rg = raygenIn[y*o_ubo.image_width + x];
				if (rg.tid != htid) {
					border = true;
				}
			}
		}
		if (border) {
			imageStore(outputImage, ivec2(rx, ry), hcolor);
		} else {
			vec4 oldc = imageLoad(outputImage, ivec2(rx, ry));
			imageStore(outputImage, ivec2(rx, ry), mix(oldc, hcolor, mixfactor));
		}
    }
}

void highlight_rendered_edge(uint htid) {
	int rx = int(gl_GlobalInvocationID.x%o_ubo.image_width);
    int ry = int(gl_GlobalInvocationID.x/o_ubo.image_width);
    if (htid != -1 && raygenIn[gl_GlobalInvocationID.x].tid == htid) {
        int radius = 2;
		int minx = 0;
		int miny = 0;
		int maxx = rx;
		int maxy = ry;
		if (rx > radius) minx = rx - radius;
		if (ry > radius) miny = ry - radius;
		if (maxx + radius < o_ubo.image_width) maxx += radius;
		if (maxy + radius < o_ubo.image_height) maxy += radius;
		bool border = false;
		for (int x = minx; x < maxx; x++) {
			for (int y = miny; y < maxy; y++) {
				RayGenerator rg = raygenIn[y*o_ubo.image_width + x];
				if (rg.tid != htid) {
					border = true;
				}
			}
		}
		if (border) {
			imageStore(outputImage, ivec2(rx, ry), highlight_color);
		} else {
			vec4 oldc = imageLoad(outputImage, ivec2(rx, ry));
			imageStore(outputImage, ivec2(rx, ry), mix(oldc, highlight_color, mixfactor));
		}
    }
}

void highlight_vertex(uint hvid, vec2 vpos) {
    if (hvid != -1) {
	    int rx = int(gl_GlobalInvocationID.x%o_ubo.image_width);
        int ry = int(gl_GlobalInvocationID.x/o_ubo.image_width);
        vec4 color = highlight_color;
        if (vertexIn[hvid].w != 0) color = lock_color;
        if (length(vec2(rx, ry) - vpos) < 3.0) {
			imageStore(outputImage, ivec2(rx, ry), color);
        }
    }
}

void outline_triangle() {
	int rx = int(gl_GlobalInvocationID.x%o_ubo.image_width);
    int ry = int(gl_GlobalInvocationID.x/o_ubo.image_width);
    uint tid = raygenIn[gl_GlobalInvocationID.x].tid;
    float d = raygenIn[gl_GlobalInvocationID.x].distance / length(g_ubo.maxBB - g_ubo.minBB);
    if (tid != -1) {
        int radius = 1;
        int minx = 0;
        int miny = 0;
        int maxx = rx;
        int maxy = ry;
        if (rx > radius) minx = rx - radius;
		if (ry > radius) miny = ry - radius;
		if (maxx + radius < o_ubo.image_width) maxx += radius;
		if (maxy + radius < o_ubo.image_height) maxy += radius;
		bool border = false;
		for (int x = minx; x < maxx; x++) {
			for (int y = miny; y < maxy; y++) {
				RayGenerator rg = raygenIn[y*o_ubo.image_width + x];
				if (rg.tid != tid) {
					border = true;
				}
			}
		}
		if (border) {
			vec4 oldc = imageLoad(outputImage, ivec2(rx, ry));
            vec4 newc = vec4(0.1, 0.1, 0.1, 1.0);
            float vdist = vhighlight_radius;
            vec3 mixc = vec3(0);
            float vsum = 0;
            if (o_ubo.single_selected_vid != -1) {
                vdist = length(selected_vertex_position - vec2(rx, ry));
                float swapdist = vhighlight_radius - vdist;
                if (vdist < vhighlight_radius) {
                    if (vertexIn[o_ubo.single_selected_vid].w != 0) {
                        mixc += swapdist * vec3(lock_color);
                    } else {
                        mixc += swapdist * vec3(highlight_color);
                    }
                    vsum += swapdist;
                }
            }
            if (o_ubo.mode == VERTEX_SELECT && hovered_tid != o_ubo.single_selected_vid && hovered_tid != -1) {
                float olddist = vdist;
                vdist = length(vertex_position - vec2(rx, ry));
                float swapdist = vhighlight_radius - vdist;
                if (vdist < vhighlight_radius) {
                    if (vertexIn[hovered_tid].w != 0) {
                        mixc += swapdist * vec3(lock_color);
                    } else {
                        mixc += swapdist * vec3(highlight_color);
                    }
                    vsum += swapdist;
                }
                vdist = min(vdist, olddist);
            }
            if (vdist < vhighlight_radius) {
                float mixing = 1.0 - (vdist / vhighlight_radius);
                mixing = mixing*mixing*mixing;
                newc = mix(newc, vec4(mixc / vsum, 1.0), mixing);
            }
			imageStore(outputImage, ivec2(rx, ry), mix(oldc, newc, min(1.0 / d, 1.0)));
        }
    }
}

void highlight_edge(uint v1, uint v2, bool orient) {
    if (v1 == -1 || v2 == -1) return;
    uint tid = raygenIn[gl_GlobalInvocationID.x].tid;
    if (tid == -1) return;
	int rx = int(gl_GlobalInvocationID.x%o_ubo.image_width);
    int ry = int(gl_GlobalInvocationID.x/o_ubo.image_width);
    Ray ray = create_ray(vec2(rx, ry));
    Triangle tri = triangleIn[tid];
    vec3 A = vertexIn[tri.a].xyz;
    vec3 B = vertexIn[tri.b].xyz;
    vec3 C = vertexIn[tri.c].xyz;
    vec3 e1 = B - A;
    vec3 e2 = C - A;
    vec3 h = cross(ray.direction, e2);
    float a = dot(e1, h);
    if (abs(a) < EPS) return;
    float f = 1.0 / a;
    vec3 s = ray.position - A;
    float u = f * dot(s, h);
    if (u < 0.0 || u > 1.0) return;
    vec3 q = cross(s, e1);
    float v = f * dot(ray.direction, q);
    if (v < 0.0 || (u + v) > 1.0) return;
    float w = 1.0 - u - v;
    float edge_eps = 0.05;
    bool highlight = false;
    if ((v1 == tri.a && v2 == tri.b) || (v1 == tri.b && v2 == tri.a)) highlight = (v < edge_eps);
    else if ((v1 == tri.a && v2 == tri.c) || (v1 == tri.c && v2 == tri.a)) highlight = (u < edge_eps);
    else if ((v1 == tri.b && v2 == tri.c) || (v1 == tri.c && v2 == tri.b)) highlight = (w < edge_eps);
    if (highlight) {
        vec4 color = highlight_color;
        if (orient) {
            float t = 0.0;
            if ((v1 == tri.a && v2 == tri.b) || (v1 == tri.b && v2 == tri.a)) {
                t = u / (u + w);
                if (v1 == tri.b && v2 == tri.a) t = 1.0 - t;
            }
            else if ((v1 == tri.a && v2 == tri.c) || (v1 == tri.c && v2 == tri.a)) {
                t = v / (v + w);
                if (v1 == tri.c && v2 == tri.a) t = 1.0 - t;
            }
            else if ((v1 == tri.b && v2 == tri.c) || (v1 == tri.c && v2 == tri.b)) {
                t = v / (u + v);
                if (v1 == tri.c && v2 == tri.b) t = 1.0 - t;
            }
            color = mix(vec4(1,0,0,1), vec4(0,0,1,1), t);
        }
		imageStore(outputImage, ivec2(rx, ry), color);
    }
}

void main() {
    calculate_highlight_color();
    outline_triangle();
    if (o_ubo.mode == TRIANGLE_SELECT)
        highlight_triangle(hovered_tid);
    else if (o_ubo.mode == VERTEX_SELECT)
        highlight_vertex(hovered_tid, vertex_position);
    else if (o_ubo.mode == EDGE_SELECT && ubo.geomode == 0)
        highlight_edge(hovered_edge_v1, hovered_edge_v2, false);
    else if (o_ubo.mode == EDGE_SELECT)
        highlight_rendered_edge(hovered_tid);
    if (ubo.geomode == 0) {
	    if (o_ubo.mode != TRIANGLE_SELECT || hovered_tid != o_ubo.single_selected_tid)
    		highlight_triangle(o_ubo.single_selected_tid);
    	if (o_ubo.mode != VERTEX_SELECT || hovered_tid != o_ubo.single_selected_vid)
    		highlight_vertex(o_ubo.single_selected_vid, selected_vertex_position);
        if (o_ubo.mode != EDGE_SELECT || (hovered_edge_v1 != o_ubo.single_selected_edge_v1 || hovered_edge_v2 != o_ubo.single_selected_edge_v2))
            highlight_edge(o_ubo.single_selected_edge_v1, o_ubo.single_selected_edge_v2, true);
    } else if (o_ubo.single_selected_eid != -1 && (o_ubo.mode != EDGE_SELECT || hovered_tid != o_ubo.single_selected_eid)) {
        highlight_rendered_edge(o_ubo.single_selected_eid);
    }
}
