#version 450

struct Edge {
    uint a;
    uint b;
    uint f1e1;
    uint f1e2;
    uint f2e1;
    uint f2e2;
    uint f3e1;
    uint f3e2;
    uint f4e1;
    uint f4e2;
    int flow;
};

layout(binding = 0) buffer EdgeSSBOIn {
    Edge edgeIn[ ];
};

layout(push_constant) uniform PushConstants {
    uint elements;
    uint bitstart;
    uint skipstart;
    uint skipsize;
    uint prevstart;
    uint prevsize;
} pc;

layout (local_size_x = 256, local_size_y = 1, local_size_z = 1) in;

int calcdegree(Edge e) {
    int degree = 0;
    uint candidates[4] = { e.f1e1, e.f2e1, e.f3e1, e.f4e1 };
    for (int i = 0; i < 4; i++) if (candidates[i] != -1) degree++;
    return degree;
}

void pullflow(uint comingfrom, inout Edge goingto) {
    Edge cfrom = edgeIn[comingfrom];
    if (abs(cfrom.flow) > calcdegree(cfrom)) {
        if (cfrom.a == goingto.a || cfrom.a == goingto.b) {
            if (cfrom.a == goingto.a) {
                goingto.flow--; // maybe need to reverse +/-?
            } else {
                goingto.flow++;
            }
        } else {
            if (cfrom.b == goingto.b) {
                goingto.flow--;
            } else {
                goingto.flow++;
            }
        }
    }
}

bool inskip(uint e) {
    return e >= pc.skipstart && e < pc.skipstart + pc.skipsize;
}

bool inprev(uint e) {
    return e >= pc.prevstart && e < pc.prevstart + pc.prevsize;
}

void main() {
    uint eid = gl_GlobalInvocationID.x;
    if (pc.skipsize == 0) {
        eid = pc.prevstart + gl_GlobalInvocationID.x;
    } else if (gl_GlobalInvocationID.x >= pc.skipstart) {
        eid = pc.skipsize + gl_GlobalInvocationID.x;
    }
    Edge e = edgeIn[eid];
    if (inprev(eid)) {
        int degree = calcdegree(e);
        if (abs(e.flow) > degree) {
            if (e.flow < 0) e.flow += degree;
            else e.flow -= degree;
        }
    }
    if (pc.skipsize != 0) {
        uint candidates[8] = { e.f1e1, e.f1e2, e.f2e1, e.f2e2, e.f3e1, e.f3e2, e.f4e1, e.f4e2 };
        for (int i = 0; i < 8; i++) {
            if (inskip(candidates[i]))
                pullflow(candidates[i], e);
        }
    }
    edgeIn[eid].flow = e.flow;
}
